version: '3.2'

volumes:
  peer2org1:

networks:
  basic:
    external: true

services:

  peer2org1:
    image: hyperledger/fabric-peer
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == $HOSTNAME
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2org1
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2org1:7051
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_EXECUTETIMEOUT=60
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=basic
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # Add --peer-chaincodedev=true
    command: peer node start
    ports:
      - published: 7151
        target: 7051
        mode: host
      - published: 7153
        target: 7053
        mode: host
    volumes:
        - /var/run/:/host/var/run/
        - /opt/PROLEUM/fabric/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/etc/hyperledger/msp/peer
        - /opt/PROLEUM/fabric/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - /opt/PROLEUM/fabric/config:/etc/hyperledger/configtx
        - peer2org1:/var/hyperledger/production
    networks:
      - basic

  cli:
    image: hyperledger/fabric-tools
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == $HOSTNAME
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer2org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /opt/PROLEUM/chaincode/:/opt/gopath/src/github.com/petroleum/
      - /opt/PROLEUM/fabric/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - basic
